title : "####################--Robot'configuration--##################"
line0 : "#############################################################"

velLine : 
    brief:  "����㶯���٣�ƽ��(����)"
    value: 1          
    
velRotate : 
    brief:  "����㶯���٣���ת(��)"
    value: 0.05       

end_vel_limit: 
    brief: "�ؽ��˶�����"
    value: [1,1,1,0.05,0.05,0.05]

end_vel_position: 
    brief: "ĩ���˶�����"
    value: [1,1,1,0.05,0.05,0.05]

line1 : "#############################################################"

CYLINDER_INDEX : 
    brief:  "�Ƹ˹ؽ��������"
    value: 5     
STEER_LEFT_INDEX : 
    brief:  "���������"
    value: 11
STEER_RIGHT_INDEX : 
    brief:  "�Ҷ�������"
    value: 13
WHEEL_LEFT_INDEX : 
    brief:  "������������"
    value: 12
WHEEL_RIGHT_INDEX : 
    brief:  "������������"
    value: 14
TOOL_LIFTING: 
    brief:  "������������"
    value: 4      

Lift_Distance_In_Parallel : 
    brief:  "��ƽ״̬�¾�����λ��"
    value: 11.0
Max_Deviation_In_Parallel : 
    brief:  "��ƽ�������ƫ��"
    value: 50.0    
Min_Deviation_In_Parallel : 
    brief:  "��ƽ������Сƫ��"
    value: 3.0     

Distance_work : 
    brief:  "λ��"
    value: 10        

Lift_Distance_In_FitBoard : 
    brief:  "����״̬�¾�����λ��"
    value: 6.0     
Max_Deviation_In_FitBoard : 
    brief:  "��������ƫ��"
    value: 20.0    
Min_Deviation_In_FitBoard : 
    brief:  "��������ƫ��"
    value: 6.0     

Line_Deviation_Threshold : 
    brief:  "���ߵ�������ƫ��"
    value: 2.0     

line2 : "#############################################################"

robot_ip: 
    brief:  "��������λ��IP"
    value: "192.168.1.130"

robot_port:
    brief:  "��������λ���˿�"
    value: 6999


IOA_ip: 
    brief:  "IOA��IP"
    value: "192.168.1.201"

IOA_port: 
    brief:  "IOA��˿�"
    value: 5999

IOB_ip:
    brief: "IOB��IP"    
    value: "192.168.1.202"

IOB_port: 
    brief:  "IOB��˿�"
    value: 5999

line3 : "#############################################################"